### ISSUE TITLE
这个挂件是否只能用于yesplaymusic

### ISSUE THREAD

**Issue by sf467** [chiyuki0325/PlasmaDesktopLyrics#1]
这个挂件是否只能用于yesplaymusic

**Comment by chiyuki0325** [comment]
歌词的获取来源：
- 若为本地音乐播放器，则会尝试从音乐文件头 / lrc 文件读取歌词
- 如果不是本地播放器，或找不到歌词，则会在网易云音乐搜索同名歌曲，并且获取歌词
其中，专门对 YesPlayMusic 做了适配，因为 YesPlayMusic 有一个本地 API，可以直接从上面拿歌词。

如果小组件不能用，请检查本地后台服务是否在运行：
```
systemctl status --user plasma-desktop-lyrics.service
```

**Comment by sf467** [comment]
好的我试试，看起来这个挂件的功能确实是我一直在找但是没有找到的，
太激动了
总之十分感谢！！！

**Comment by chiyuki0325** [comment]
另外，如果有浏览器不小心被当成播放器匹配到，是可以通过在配置文件添加对应条目来禁用的。请参见 config 文件夹中的代码。
因为时间紧迫，所以没写文档，抱歉 😥

**Comment by sf467** [comment]
> 另外，如果有浏览器不小心被当成播放器匹配到，是可以通过在配置文件添加对应条目来禁用的。请参见 config 文件夹中的代码。 因为时间紧迫，所以没写文档，抱歉 😥

那是不是就是说，我用浏览器播放网络歌曲，也可以匹配我本地的歌词？
太棒了！！
