### ISSUE TITLE
关于歌词的翻译

### ISSUE THREAD

**Issue by sf467** [chiyuki0325/PlasmaDesktopLyrics#2]
因为自己实在没技术，提不了pr ，只能提issue了
首先感谢作者的创作

有关双语歌词：lrc文件中与原歌词时间轴一致的下一句歌词可以看作是原歌词的翻译，在这个挂件中，只能随机显示其中一个，要么是原歌词，要么是翻译。希望可以像yesplayermusic那样，左侧显示歌词，右侧显示翻译

**Comment by chiyuki0325** [comment]
Fixed in d1684dbc6359accf81b4c5af3613b3e5ec72a3ab.
