### ISSUE TITLE
通信机制似乎可以优化

### ISSUE THREAD

**Issue by ExplodingDragon** [chiyuki0325/PlasmaDesktopLyrics#5]
或许可以将 WebSocket 改为轮训或者用 unix socket？，这样可以不需要 qt-websocket 了

**Comment by ExplodingDragon** [comment]
而且 ws 连接断开后不会重连 ....

**Comment by chiyuki0325** [comment]
Plasma 小挂件貌似没权限读 unix socket ...  
如果有除了 websocket 之外更好的通信方案，欢迎提交 pr。
